spring:
  cloud:
    gcp:
      project-id: hookahshopee
      sql:
        instance-connection-name: hookahshopee:europe-west3:hookah-shopee-db
        database-name: hookah_shopee

  datasource:
    url: jdbc:mysql://google/hookah_shopee?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=hookahshopee:europe-west3:hookah-shopee-db&useSSL=false
    username: vovka
    password: qw&UZ**485$xX9
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    sql-script-encoding: UTF-8

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    enabled: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 6MB

file:
  upload-dir: uploads

server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: /

  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/cert.pfx
    enabled: false
    key-store-password: 12345678

jwt:
  token:
    secret: secret-jwt
    expired: 3600000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
