spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=HookahShopee;useUnicode=yes&characterEncoding=UTF-8
    username: sa
    password: 12345678qwa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialization-mode: always
    sql-script-encoding: UTF-8

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    enabled: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 6MB

file:
  upload-dir: uploads

server:
  port: 8080
  http2:
    enabled: true
  servlet:
    context-path: /

  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/cert.pfx
    enabled: false
    key-store-password: 12345678

jwt:
  token:
    secret: secret-jwt
    expired: 3600000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    displayRequestDuration: true
